datos_canciones = [
    {"clave": 1, "nombre_cancion": "Shape of You", "nombre_cantante": "Ed Sheeran",
     "genero": "Pop", "album": "Divide", "precio": 20.0},
    {"clave": 2, "nombre_cancion": "Blinding Lights", "nombre_cantante": "The Weeknd",
     "genero": "R&B", "album": "After Hours", "precio": 22.5},
    {"clave": 3, "nombre_cancion": "Bohemian Rhapsody", "nombre_cantante": "Queen",
     "genero": "Rock", "album": "A Night at the Opera", "precio": 25.0},
    {"clave": 4, "nombre_cancion": "Despacito",
     "nombre_cantante": "Luis Fonsi ft. Daddy Yankee", "genero": "Reggaeton",
     "album": "Vida", "precio": 18.0},
    {"clave": 5, "nombre_cancion": "Lose Yourself", "nombre_cantante": "Eminem",
     "genero": "Hip-Hop", "album": "8 Mile Soundtrack", "precio": 23.0},
    {"clave": 6, "nombre_cancion": "Havana",
     "nombre_cantante": "Camila Cabello ft. Young Thug", "genero": "Pop",
     "album": "Camila", "precio": 19.5},
    {"clave": 7, "nombre_cancion": "Hotel California", "nombre_cantante": "Eagles",
     "genero": "Rock", "album": "Hotel California", "precio": 26.0},
    {"clave": 8, "nombre_cancion": "Tusa", "nombre_cantante": "Karol G ft. Nicki Minaj",
     "genero": "Reggaeton", "album": "KG0516", "precio": 17.0},
    {"clave": 9, "nombre_cancion": "Someone Like You", "nombre_cantante": "Adele",
     "genero": "Pop", "album": "21", "precio": 21.0},
    {"clave": 10, "nombre_cancion": "Smells Like Teen Spirit",
     "nombre_cantante": "Nirvana", "genero": "Grunge", "album": "Nevermind",
     "precio": 24.0}
]
